# This file was generated by GoReleaser. DO NOT EDIT.
cask "chief" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "8625843d9e306d60c4d952ff8cf5ae2124bd254b401a7356c4b699e28283f25c"
      url "https://github.com/Storytell-ai/chief-cli/releases/download/v#{version}/chief-cli_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "d60d1c970adda2a50b9739cbcbfac8e2134e0cf82c2538f1e330f439e4c10b75"
      url "https://github.com/Storytell-ai/chief-cli/releases/download/v#{version}/chief-cli_#{version}_Darwin_arm64.tar.gz"
    end
  end

  name "chief"
  desc "Chief command-line interface"
  homepage "https://github.com/Storytell-ai/chief-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chief"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/chief"]
    end
  end

  # No zap stanza required

end
