# This file was generated by GoReleaser. DO NOT EDIT.
cask "chief" do
  version "0.5.0"

  on_macos do
    on_arm do
      sha256 "4ea3598ca4489a9447e17265c6dfc530d0d07f25c017d375cc0f63ad79cdd692"
      url "https://github.com/Storytell-ai/chief-cli/releases/download/v#{version}/chief-cli_#{version}_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "3c399d3f191788f261b4ab0ba15acdac329c238fd7bc632cb364c8b8b9a86ba4"
      url "https://github.com/Storytell-ai/chief-cli/releases/download/v#{version}/chief-cli_#{version}_Darwin_x86_64.tar.gz"
    end
  end

  name "chief"
  desc "Chief command-line interface"
  homepage "https://github.com/Storytell-ai/chief-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chief"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/chief"]
    end
  end

  # No zap stanza required
end
