# This file was generated by GoReleaser. DO NOT EDIT.
cask "chief-mcp" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "e7ee67ffce69f82927c979f82274d6dd7df7bd025a598427e7ded1d698b8cdfa"
      url "https://github.com/Storytell-ai/chief-mcp/releases/download/v#{version}/chief-mcp_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "1d8d3410393ba69cb7a8fe7fe0fd59571cfad3be6b8fd47b62ba5224c5ce23af"
      url "https://github.com/Storytell-ai/chief-mcp/releases/download/v#{version}/chief-mcp_#{version}_Darwin_arm64.tar.gz"
    end
  end

  name "chief-mcp"
  desc "Chief MCP server"
  homepage "https://github.com/Storytell-ai/chief-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chief-mcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/chief-mcp"]
    end
  end

  # No zap stanza required

end
