# This file was generated by GoReleaser. DO NOT EDIT.
cask "chief" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "10fbb63ce9d57414a6ec712ebb307ac7f069fe21b86413c92835fcb6589e014c"
      url "https://github.com/Storytell-ai/chief-cli/releases/download/v#{version}/chief-cli_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "baa237ee9a56e361a7114c4e0a1adcff843308fcd31be6b4b9404fde84bbc786"
      url "https://github.com/Storytell-ai/chief-cli/releases/download/v#{version}/chief-cli_#{version}_Darwin_arm64.tar.gz"
    end
  end

  name "chief"
  desc "Chief command-line interface"
  homepage "https://github.com/Storytell-ai/chief-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chief"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/chief"]
    end
  end

  # No zap stanza required

end
