# This file was generated by GoReleaser. DO NOT EDIT.
cask "chief-mcp" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "3de2972ec6ebd47597168a217b13c4401ff6e115772d890484ef730518a9ccc3"
      url "https://github.com/Storytell-ai/chief-mcp/releases/download/v#{version}/chief-mcp_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "9702630133fcf9ed31aefa54e3a25d07fccf42bc9682de799f94811a6d866865"
      url "https://github.com/Storytell-ai/chief-mcp/releases/download/v#{version}/chief-mcp_#{version}_Darwin_arm64.tar.gz"
    end
  end

  name "chief-mcp"
  desc "Chief MCP server"
  homepage "https://github.com/Storytell-ai/chief-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chief-mcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/chief-mcp"]
    end
  end

  # No zap stanza required

end
