# This file was generated by GoReleaser. DO NOT EDIT.
cask "chief-mcp" do
  version "0.7.0"

  on_macos do
    on_intel do
      sha256 "88c4b81f0893cb1f6062aa678dd3c6a12dd4aec55ae59d2e466ec4cc15ff1e88"
      url "https://github.com/Storytell-ai/chief-mcp/releases/download/v#{version}/chief-mcp_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "8e9af0476eb4b0165fb3c9b5cd1e5c61040ed0f58d88d5e8788936bd34b0f1d6"
      url "https://github.com/Storytell-ai/chief-mcp/releases/download/v#{version}/chief-mcp_#{version}_Darwin_arm64.tar.gz"
    end
  end

  name "chief-mcp"
  desc "Chief MCP server"
  homepage "https://github.com/Storytell-ai/chief-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chief-mcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/chief-mcp"]
    end
  end

  # No zap stanza required

end
